{{- if .Values.notificationService.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  labels:
    app: notification-service
type: Opaque
data:
  DB_USER: {{ .Values.postgres.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
{{- end }}
