apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  labels:
    app: notification-service
type: Opaque
data:
  DB_USER: bWljcm9zZXJ2aWNlcw==
  DB_PASSWORD: bWljcm9zZXJ2aWNlczEyMw==
