apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app: frontend
data:
  VITE_USER_SERVICE_URL: "http://user-service:8001"
  VITE_PRODUCT_SERVICE_URL: "http://product-service:8002"
  VITE_ORDER_SERVICE_URL: "http://order-service:8003"
  VITE_NOTIFICATION_SERVICE_URL: "http://notification-service:8004"
  VITE_ANALYTICS_SERVICE_URL: "http://analytics-service:8005"
