apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  labels:
    app: product-service
data:
  PORT: "8002"
  SERVICE_NAME: "product-service"
  LOG_LEVEL: "info"
  USER_SERVICE_URL: "http://user-service:8001"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "microservices"
