{{- if .Values.productService.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  labels:
    app: product-service
data:
  PORT: {{ .Values.productService.port | quote }}
  SERVICE_NAME: "product-service"
  LOG_LEVEL: "info"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: {{ .Values.productService.dbName | quote }}
{{- end }}
