{{- if .Values.productService.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
  labels:
    app: product-service
type: Opaque
data:
  DB_USER: {{ .Values.postgres.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
{{- end }}
