apiVersion: v2
name: microservices-app
description: A Helm chart for the Microservices Multistack App
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kube-prometheus-stack
    version: "51.0.0"
    repository: "https://prometheus-community.github.io/helm-charts"
