{{- if .Values.userService.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  labels:
    app: user-service
type: Opaque
data:
  DB_USER: {{ .Values.postgres.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
{{- end }}
