apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  labels:
    app: order-service
data:
  PORT: "8003"
  SERVICE_NAME: "order-service"
  LOG_LEVEL: "INFO"
  USER_SERVICE_URL: "http://user-service:8001"
  PRODUCT_SERVICE_URL: "http://product-service:8002"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8004"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "microservices"
