{{- if .Values.orderService.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  labels:
    app: order-service
data:
  PORT: {{ .Values.orderService.port | quote }}
  SERVICE_NAME: "order-service"
  LOG_LEVEL: "info"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: {{ .Values.postgres.dbName | quote }}
{{- end }}
