{{- if .Values.orderService.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  labels:
    app: order-service
type: Opaque
data:
  DB_USER: {{ .Values.postgres.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
{{- end }}
